# Generated by Django 3.2.23 on 2023-12-22 08:16

import django.core.validators
from django.db import migrations, models
import siteapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0003_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_img',
            field=models.FileField(blank=True, upload_to='avatars/', validators=[siteapp.models.Comment.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])], verbose_name='аватар'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.FileField(blank=True, upload_to='avatars/', validators=[siteapp.models.Post.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])], verbose_name='аватар'),
        ),
    ]
