# Generated by Django 3.2.23 on 2023-12-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0005_auto_20231222_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_img',
            field=models.FileField(blank=True, upload_to='comments/', verbose_name='изображение комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.FileField(blank=True, upload_to='posts/', verbose_name='изображение поста'),
        ),
    ]
