# Generated by Django 3.2.23 on 2023-12-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0007_auto_20231222_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.FileField(blank=True, upload_to='', verbose_name='qweq'),
        ),
    ]
