# Generated by Django 3.2.23 on 2023-12-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0008_comment_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
    ]
